### ISSUE TITLE
TTS support in Sonos official app

### ISSUE THREAD

**Issue by runely** [ludvigaldrin/com.svipler.athom.sonos-say#10]
Hi

Just a little heads up. Sonos official Homey app was updates today with TTS support: https://homey.app/no-no/app/com.sonos/Sonos/

**Comment by ludvigaldrin** [comment]
Haha yes. They stole my idea :). Tried to push this for production and this was the reply. 
"Dear Ludvig Aldrin, Thank you for submitting your app Sonos Say for review. Unfortunately, your app has not passed the certification process, due to the following: — Your app is an extension for an already existing app. Ideally we’d like to see one app per brand in the App Store. This makes it clear and easy for the end-users, which app they need. However we do feel that the extra features your app offers, are a great addition to the existing app. That is why we will look into adding such features to the original app. So you and other users can make use of it, without having to install a new app and pairing their devices again. We appreciate your efforts, if you have any other feature suggestions for Homey or Athom apps please put in a feature request via support."

So I guess they added it after seeing my solution. In the official app its only supported on newer hardware so I guess you still need my app for S1 hardware.
